version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gses
      MYSQL_USER: gses
      MYSQL_PASSWORD: gses
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 3

